import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";



export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
       <Layout className='pt-0'>
         <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="Gopinath" className='w-full h-auto'
              priority
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center sefl-center'>
              <AnimatedText text="People don't care about what you say, they care about what you build." className='!text-5xl !text-left'/>
              <p className='my-4 text-base font-medium'>
              As an upcoming developer, I am dedicated to turning my ideas into innovative projects. 
I&apos;m trying to do some creative projects shortly, and I&apos;ll update as soon as possible.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/Gopinath M - Resume.pdf" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                border-2 border-solid border-transparent hover:border-dark 
                
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light
                "
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:darlinggopi09@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >Contact</Link>
              </div>
            </div>
         </div>
       </Layout>
      <div className='absolute right-8 bottom-8 inline-block w-24'>
        <Image src={lightBulb} alt="Gojo" className='w-full h-auto'/>
      </div>
      </main>
      </>
  )
}